import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "@/components/layout/Navbar"
import { cn } from "@/lib/utils";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("min-h-screen font-sans antialiased", geistSans.variable, geistMono.variable)}
      >
        <Navbar />
        <main className="max-w-7xl mx-auto px-4 sm:px-8 py-8"> 
          {children}
        </main>
        <footer className="py-4 text-center bg-gray-200">
          <p className="text-sm">© 2023 Your Company Name. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
